name: Documentation

on:
  push:
    branches:
      - main
      - develop # To remove once the library is available in main branch
      - feature/documentation # To remove once this branch is done

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          format: html
          module-name: CompositionalLayoutDSL
          output: "Documentation"
          base-url: /CompositionalLayoutDSL/
      # The documentation step is generating files as root, and so are not readable by the runner without that fix
      - name: Fix owner of generated files
        run: sudo chown $USER -R ./Documentation
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./Documentation
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
